travis:
  secure:
    BINSTAR_TOKEN: kDbdUCRUCIvmesAMpQOR/impwsnQYZak+VZ3+EncFFOofDt73hEJJQQA2Jg6Q68ujmi0dVk+6Pw5vFHWmDqTnvtzh/7Bysaaws1gUxlyU+Kh+dDonh3lgKzvXB9lLYXYMjgCuLMUzy/u5PSKHz+/Kmn/ia3+b1l/4PqM0EIOdnUZsQSVuo8llpB25pYO6+odpI4C/YuTlfUy1MMemutfdURC99XPX+Ne4B6AdMQOtobv+cIbxM0p6TzUw8/Q8T07isMpP+iO+JDTxOCSwT6BN3xewX8hQw9H7/GKtYtJYP98XbbMJaOAd1+64REAqXdVf7v88p2c0TAp/vaqfaVIqcQHDn+Zv1oWCIsn9IeTUGbODbquDDI0U+Ia8XKPMh0WyBGQAn9QamDv1orKi3/vC8z5G+HHtYgab0xhgNT2VMh5dJ3PXJ2Hk0q9BpbRTEAsP4UOFbOvaki03CogItmXcwNImXx3k2n3N9WhuLRwCS2FnTPy3VZgDl+PxfOdNls3DFxi12i+peZXnqBxzgSDlDaU10JWGaHksm0Y0W6KWowFr2ge7aD02eOc15ptKAXF2GG5F+O+fjJvKUQIHYy14Zlm9cv0ZjLG9bVQ+drmJOtw7MZ6vcS21N1KMe8tdyMNRrW0+MCUkZ093C8yIv5ZvHc3hDRyRQBStzOH35i5jYw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
